In [1]:
import pandas as pd

# **CEPEA**

In [4]:
cepea_diario = pd.read_parquet("df_daily-cepea.parquet")
cepea_diario.head()

        Data  À vista R$  À vista US$  indicador
0 2016-01-04       78.14        19.30     parana
1 2016-01-04       81.64        20.17  paranagua
2 2016-01-05       82.26        20.61  paranagua
3 2016-01-05       79.00        19.79     parana
4 2016-01-06       78.55        19.55     parana

In [5]:
cepea_semanal = pd.read_parquet("df_weekly-cepea.parquet")
cepea_semanal.head()

,indicador,semana,preco_rs_medio,preco_rs_fechamento,preco_rs_max,preco_rs_min,preco_usd_medio,preco_usd_fechamento,preco_usd_max,preco_usd_min,qtd_dias_semana,retorno_rs_1w,retorno_usd_1w
0,parana,2016-01-15,80.298,79.79,80.76,79.79,19.940,19.70,20.22,19.70,5,0.010512,0.006643
1,paranagua,2016-01-15,84.822,84.42,85.70,83.35,21.066,20.85,21.39,20.59,5,0.015152,0.011645
2,paranagua,2016-01-22,83.220,82.94,83.98,82.39,20.344,20.19,20.83,20.02,5,-0.017531,-0.031655
3,parana,2016-01-22,78.294,77.81,79.55,77.81,19.144,18.95,19.74,18.78,5,-0.024815,-0.038071
4,parana,2016-01-29,76.572,75.64,77.28,75.64,18.812,18.79,18.92,18.67,5,-0.027888,-0.008443

# **DOLAR**

In [7]:
dolar_diario = pd.read_parquet("df_daily-dolarptax.parquet")
dolar_diario.head()

        data   valor
0 2016-06-06  3.5098
1 2016-06-07  3.4745
2 2016-06-08  3.3898
3 2016-06-09  3.3817
4 2016-06-10  3.4261

In [8]:
dolar_semanal = pd.read_parquet("df_weekly-dolarptax.parquet")
dolar_semanal.head()

,dolar_medio_semana,dolar_fechamento_semana,dolar_max_semana,dolar_min_semana
data,,,,
2016-06-10,3.43638,3.4261,3.5098,3.3817
2016-06-17,3.46832,3.4372,3.4904,3.4372
2016-06-24,3.37840,3.3772,3.3897,3.3533
2016-07-01,3.28064,3.2298,3.3934,3.2098
2016-07-08,3.29964,3.2968,3.3388,3.2480

# **COMEX (EXPORTAÇÕES)**

**ano_mes**

Mês de referência da exportação.
Exemplo:
2020-05-01
significa:
Exportações brasileiras de soja de Maio/2020.

**volume_kg**

Quantidade total exportada de soja em quilogramas.
Exemplo:
10.000.000 kg

10 mil toneladas

**volume_ton**

Quantidade total exportada convertida para toneladas.
Fórmula:
volume_ton = volume_kg / 1000

**valor_fob_usd**

Valor total exportado em dólares FOB.

FOB significa:
Free On Board
ou seja:
valor da mercadoria embarcada no porto brasileiro

**preco_implicito_usd_ton**

Preço médio implícito da soja exportada.
Fórmula:
valor_fob_usd / volume_ton
Exemplo:
US$ 400 / tonelada

In [9]:
exportacoes_comex = pd.read_parquet("fact_exports_monthly.parquet")
exportacoes_comex.head()

,ano_mes,volume_kg,volume_ton,valor_fob_usd,preco_implicito_usd_ton
0,2016-01-01,394419947,3.944199e+05,147623117,374.279035
1,2016-02-01,2036796148,2.036796e+06,715302008,351.189788
2,2016-03-01,8373802762,8.373803e+06,2924358377,349.227043
3,2016-04-01,10085881032,1.008588e+07,3532371105,350.229305
4,2016-05-01,9915098848,9.915099e+06,3600309132,363.113791

# **CONAB**

**safra**

Identificador da safra agrícola.
Exemplo:
2024/25

**area_mil_ha**

Área plantada de soja em milhares de hectares.
Exemplo:
45000
45 milhões de hectares

**produtividade_kg_ha**

Quantidade produzida por hectare plantado.
Exemplo:
3500 kg/ha

**producao_mil_ton**

Produção total da safra em milhares de toneladas.
Exemplo:
160000
160 milhões de toneladas

**safra_inicio**

Ano de início da safra.
Exemplo:
2024

**safra_fim**

Ano de término da safra.
Exemplo:
2025

In [10]:
conab = pd.read_parquet("fact_supply_safra.parquet")
conab.head()

,safra,area_mil_ha,produtividade_kg_ha,producao_mil_ton,safra_inicio,safra_fim
0,1976/77,6949.0,1747.733487,12145.0,1976,1977
1,1977/78,7780.0,1250.128535,9726.0,1977,1978
2,1978/79,8151.0,1251.380199,10200.0,1978,1979
3,1979/80,8755.9,1700.270675,14887.4,1979,1980
4,1980/81,8693.4,1781.213334,15484.8,1980,1981

# **NASA POWER**

**chuva_soja_1w**	Chuva semanal ponderada pelas regiões produtoras

**temp_media_soja_1w**	Temperatura média ponderada

**temp_max_soja_1w**	Temperatura máxima ponderada

**temp_min_soja_1w**	Temperatura mínima ponderada

**umidade_soja_1w**	Umidade ponderada

**dias_secos_soja_1w**	Dias secos ponderados

**dias_calor_extremo_soja_1w**	Dias de calor extremo ponderados

**n_pontos**	Quantidade de pontos climáticos usados

**stress_chuva**	Quanto menor a chuva histórica, maior o stress

**stress_calor**	Quanto maior o calor, maior o stress

**stress_dias_secos**	Quanto mais dias secos, maior o stress

**stress_climatico_soja**	Índice final de stress climático da soja

In [17]:
df1 = pd.read_parquet('fact_weather_daily_nasa_power.parquet')
df2 = pd.read_parquet('fact_weather_soy_index_weekly.parquet')
df3 = pd.read_parquet('fact_weather_weekly_location_nasa_power.parquet')

In [18]:
df1.head()

,data,uf,local,latitude,longitude,peso,chuva_mm,temp_media,temp_max,temp_min,umidade_media
0,2016-01-01,MT,sorriso,-12.545,-55.711,0.3,22.48,28.36,32.15,23.87,73.69
1,2016-01-02,MT,sorriso,-12.545,-55.711,0.3,7.98,24.64,27.88,23.11,92.60
2,2016-01-03,MT,sorriso,-12.545,-55.711,0.3,3.88,24.62,28.80,21.67,88.25
3,2016-01-04,MT,sorriso,-12.545,-55.711,0.3,10.64,26.24,31.14,21.65,85.15
4,2016-01-05,MT,sorriso,-12.545,-55.711,0.3,19.89,24.73,27.30,23.00,94.35

In [19]:
df2.head()

,semana,chuva_soja_1w,temp_media_soja_1w,temp_max_soja_1w,temp_min_soja_1w,umidade_soja_1w,dias_secos_soja_1w,dias_calor_extremo_soja_1w,n_pontos,stress_chuva,stress_calor,stress_dias_secos,stress_climatico_soja
0,2016-01-01,10.3431,26.193800,29.9104,22.5117,78.542500,0.00,0.0,7,0.722936,0.170642,0.001835,0.360092
1,2016-01-08,53.8239,24.869729,30.7210,20.6299,86.791300,0.94,0.0,7,0.053211,0.278899,0.009174,0.082936
2,2016-01-15,82.1888,24.832886,29.9269,21.2143,87.844529,1.55,0.0,7,0.003670,0.177982,0.064220,0.059725
3,2016-01-22,37.4496,24.274786,30.2532,19.0845,84.233157,3.18,0.0,7,0.227523,0.214679,0.392661,0.282752
4,2016-01-29,34.2159,25.036871,30.7911,19.4414,84.769857,2.70,0.1,7,0.280734,0.289908,0.295413,0.287706

In [20]:
df3.head()

,uf,local,latitude,longitude,peso,semana,chuva_mm_1w,temp_media_1w,temp_max_1w,temp_min_1w,umidade_media_1w,dias_secos_1w,dias_calor_extremo_1w
0,BA,luis_eduardo_magalhaes,-12.095,-45.786,0.1,2016-01-01,1.90,27.950000,34.24,22.60,53.560000,0,0
1,BA,luis_eduardo_magalhaes,-12.095,-45.786,0.1,2016-01-08,99.27,24.605714,31.56,19.32,78.057143,0,0
2,BA,luis_eduardo_magalhaes,-12.095,-45.786,0.1,2016-01-15,79.35,23.871429,28.51,20.31,84.172857,2,0
3,BA,luis_eduardo_magalhaes,-12.095,-45.786,0.1,2016-01-22,205.64,22.958571,27.97,20.04,89.464286,0,0
4,BA,luis_eduardo_magalhaes,-12.095,-45.786,0.1,2016-01-29,105.28,23.154286,27.78,19.18,89.120000,0,0